import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  fr: {
    // Navigation
    home: 'Accueil',
    discover: 'Découverte',
    social: 'Social',
    collection: 'Collection',
    online: 'En Ligne',
    profile: 'Profil',
    logOut: 'Déconnexion',
    logIn: 'Connexion',
    
    // Home Page
    heroTitle: 'Votre Communauté Puzzle Ultime',
    heroSubtitle: 'Connectez-vous avec des milliers de passionnés de puzzles, partagez vos créations et découvrez de nouveaux défis passionnants',
    startCollection: 'Commence Ta Collection',
    exploreCollection: 'Explorer la Collection',
    featuredPuzzles: 'Puzzles en Vedette',
    mostPlayed: 'Les Plus Joués',
    monthlyEvents: 'Événements Mensuels',
    communityFeed: 'Fil de la Communauté',
    viewAll: 'Voir Tout',
    
    // Collection Page
    puzzleCollection: 'Collection de Puzzles',
    explorePuzzles: 'Explorer {count} puzzles',
    searchPuzzles: 'Rechercher des puzzles...',
    filters: 'Filtres',
    all: 'Tout',
    nature: 'Nature',
    abstract: 'Abstrait',
    urban: 'Urbain',
    space: 'Espace',
    architecture: 'Architecture',
    vintage: 'Vintage',
    animals: 'Animaux',
    art: 'Art',
    pieceCount: 'Nombre de Pièces',
    difficulty: 'Difficulté',
    easy: 'Facile',
    medium: 'Moyen',
    hard: 'Difficile',
    clearAllFilters: 'Effacer Tous les Filtres',
    mostPopular: 'Plus Populaire',
    newest: 'Plus Récent',
    highestRated: 'Mieux Noté',
    piecesLowToHigh: 'Pièces: Bas à Haut',
    piecesHighToLow: 'Pièces: Haut à Bas',
    backToTop: 'Retour en Haut',
    sortBy: 'Trier par',
    
    // Social Page
    community: 'Communauté',
    trending: 'Tendances',
    latest: 'Récent',
    following: 'Abonnements',
    createPost: 'Créer une Publication',
    whatsOnYourMind: 'Quoi de neuf?',
    shareYourThoughts: 'Partagez vos pensées...',
    uploadImage: 'Télécharger une Image',
    completedPuzzle: 'Puzzle Complété?',
    puzzleName: 'Nom du Puzzle',
    brand: 'Marque',
    pieces: 'Pièces',
    post: 'Publier',
    posting: 'Publication...',
    logInToPost: 'Veuillez vous connecter pour créer des publications et interagir avec la communauté',
    noPosts: 'Aucune publication pour le moment. Soyez le premier à partager!',
    youveReachedEnd: 'Vous avez atteint la fin!',
    communityGuidelines: 'Règles de la Communauté',
    guidelinesText: 'Soyez respectueux, partagez votre passion et aidez les autres puzzleurs. Gardons cette communauté géniale! 🧩',
    communityStats: 'Statistiques de la Communauté',
    totalPosts: 'Total Publications',
    activeToday: 'Actif Aujourd\'hui',
    live: 'En Direct',
    
    // Profile Page
    welcomeProfile: 'Bienvenue sur PuzzleWorld',
    logInToViewProfile: 'Connectez-vous pour voir votre profil, suivre les puzzles complétés et gérer votre liste de souhaits',
    joined: 'Inscrit',
    completed: 'Complétés',
    hours: 'Heures',
    achievements: 'Succès',
    wishlist: 'Liste de Souhaits',
    level: 'Niveau',
    puzzleEnthusiast: 'Passionné de Puzzles',
    puzzleExpert: 'Expert en Puzzles',
    puzzleMaster: 'Maître des Puzzles',
    noAchievements: 'Aucun succès pour le moment',
    completeToUnlock: 'Complétez des puzzles pour débloquer des badges!',
    welcomeToDashboard: 'Bienvenue sur votre tableau de bord de puzzle! Suivez vos puzzles complétés et construisez votre liste de souhaits.',
    myEvents: 'Mes Événements',
    upcomingEvents: 'Événements à venir',
    noEvents: 'Aucun événement inscrit',
    
    // Online Puzzles Page
    onlinePuzzles: 'Puzzles En Ligne',
    playInBrowser: 'Jouez aux puzzles directement dans votre navigateur',
    searchGames: 'Rechercher des jeux...',
    web: 'Web',
    mobile: 'Mobile',
    crossPlatform: 'Multi-Plateforme',
    featured: 'En Vedette',
    playNow: 'Jouer Maintenant',
    players: 'joueurs',
    trendingNow: 'Tendances Actuelles',
    popularThisWeek: 'Jeux de puzzle les plus populaires cette semaine',
    allOnlineGames: 'Tous les Jeux En Ligne',
    browseCollection: 'Parcourir notre collection complète',
    wantToAddGame: 'Vous voulez ajouter un jeu?',
    addGameText: 'Connaissez-vous un jeu de puzzle en ligne incroyable qui devrait être présenté ici? Faites-le nous savoir et nous l\'examinerons!',
    suggestGame: 'Suggérer un Jeu',
    
    // Puzzle Detail Page
    backToCollection: 'Retour à la Collection',
    playOnline: 'Jouer En Ligne',
    download: 'Télécharger',
    overview: 'Aperçu',
    leaderboard: 'Classement',
    reviews: 'Avis',
    aboutPuzzle: 'À Propos de ce Puzzle',
    avgTime: 'Temps Moyen',
    bestTime: 'Meilleur Temps',
    createdBy: 'Créé par',
    followers: 'abonnés',
    follow: 'Suivre',
    viewProfile: 'Voir le Profil',
    reportPuzzle: 'Signaler ce puzzle',
    youMightLike: 'Vous Pourriez Aussi Aimer',
    viewMore: 'Voir Plus',
    foundHelpful: 'trouvé utile',
    
    // Friends & Messages
    friendsAndMessages: 'Amis & Messages',
    manageFriendsConversations: 'Gérez vos amis et vos conversations',
    friends: 'Amis',
    messages: 'Messages',
    received: 'Reçues',
    sent: 'Envoyées',
    findFriends: 'Rechercher',
    noFriendsYet: 'Vous n\'avez pas encore d\'amis',
    addFriendsToChatPrompt: 'Ajoutez des amis pour commencer à discuter',
    conversations: 'Conversations',
    startConversation: 'Commencez la conversation !',
    selectFriendToChat: 'Sélectionnez un ami pour discuter',
    writeMessage: 'Écrivez un message...',
    noPendingRequests: 'Aucune demande reçue en attente',
    noSentRequests: 'Aucune demande envoyée en attente',
    pendingResponse: 'En attente de réponse',
    searchByNameOrCode: 'Rechercher par nom ou code ami...',
    typeAtLeast2Chars: 'Tapez au moins 2 caractères pour rechercher',
    requestSent: 'Demande envoyée',
    requestAccepted: 'Demande acceptée',
    requestDeleted: 'Demande supprimée',
    friendRemoved: 'Ami supprimé',
    addFriend: 'Ajouter',
    friend: 'Ami',
    pending: 'En attente',
    cancel: 'Annuler',
    unregisterFromEvent: 'Se désinscrire',
    unregistering: 'Désinscription...',
    eventEnded: 'Terminé',
    pastEvents: 'Événements passés',
    registerForEventsPrompt: 'Inscrivez-vous à des événements pour les voir ici',
    accountSettings: 'Paramètres du compte',
    totalPiecesAssembled: 'pièces assemblées au total',
    puzzlesCompleted: 'terminés',
    followings: 'Abonnements',
    myCollection: 'Ma Collection',
    followers: 'Abonnés',
    followings: 'Abonnements',
    // Events Page
    eventsTitle: 'Événements',
    eventsSubtitle: 'Rejoignez notre communauté lors d\'événements exclusifs',
    sortEarliest: '📅 Du plus tôt au plus tard',
    sortLatest: '📅 Du plus tard au plus tôt',
    noEventsAvailable: 'Aucun événement disponible pour le moment',
    noEventsComingSoon: 'Revenez bientôt pour découvrir nos prochains événements !',
    // Profile hardcoded strings
    piecesAssembled: 'pièces assemblées au total',
    puzzlesCompletedLabel: 'terminés',
    myCollectionTab: 'Ma Collection',
    personalTab: 'Perso',
    pastEventsLabel: 'Événements passés',
    registerForEventsHint: 'Inscrivez-vous à des événements pour les voir ici',
    eventEnded: 'Terminé',
    unregisterConfirm: 'Voulez-vous vraiment vous désinscrire de cet événement ?',
    unregisterError: 'Erreur lors de la désinscription',
    
    // Home Page hardcoded
    newPuzzlesDaily: 'Nouveaux puzzles chaque jour',
    newPuzzlesDailyLong: 'Nouveaux puzzles ajoutés chaque jour',
    scanPuzzle: 'Scanner',
    addPuzzle: 'Ajouter un puzzle',
    explore: 'Explorer',
    topPuzzles: 'Top 10 Puzzles',
    mostLiked: 'Les plus appréciés',
    mostLikedCommunity: 'Les plus appréciés de la communauté',
    latestArticles: 'Derniers articles',
    mustRead: 'À lire absolument',
    upcomingEvents: 'Événements à Venir',
    dontMissAnything: 'Ne manquez rien de la communauté',
    addYourPuzzle: 'Ajouter votre puzzle',
    scanOrAddManually: 'Scannez le code-barres ou ajoutez manuellement',
    exploreCollection: 'Explorer la collection',
    discoverThousands: 'Découvrez des milliers de puzzles',
    noPuzzleAvailable: 'Aucun puzzle disponible',
    noArticleYet: 'Aucun article pour le moment',
    noEventAvailable: 'Aucun événement disponible',
    eventsInMaintenance: 'Événements en maintenance',
    eventsMaintenanceLong: 'Les événements sont temporairement en maintenance.',
    comingSoon: 'Revenez bientôt !',
    comingSoonLong: 'Revenez bientôt pour découvrir nos prochains événements !',
    seeAll: 'Voir tout',
    upcoming: 'À venir',
    
    // Collection Page hardcoded
    communityCollection: 'Collection Communautaire',
    communityPuzzlesCount: '{count} puzzles partagés par la communauté',
    discoverMode: 'Mode Découverte',
    globalCollection: 'Collection globale',
    sortNewest: 'Nouveautés',
    sortPopular: 'Populaires',
    piecesAsc: 'Pièces ↑',
    piecesDesc: 'Pièces ↓',
    piecesAscFull: 'Pièces (croissant)',
    piecesDescFull: 'Pièces (décroissant)',
    sortBy2: 'Trier par:',
    brandFilter: 'Marque',
    allBrands: 'Toutes',
    unknownBrand: '❓ Marque inconnue',
    multipleSelect: 'Sélection multiple',
    addToCollection: 'Ajouter',
    inBox: 'Dans sa boîte',
    completed2: 'Terminé',
    myBox: 'Ma boîte',
    noPuzzleFound: 'Aucun puzzle trouvé',
    beFirstToAdd: 'Soyez le premier à ajouter un puzzle à la communauté !',
    selected: 'sélectionné',
    selectedPlural: 'sélectionnés',
    deselectAll: 'Désélect.',
    selectAll: 'Tout',
    loginToAdd: 'Connectez-vous pour ajouter à votre collection',
    addedToStatus: '{count} puzzle ajouté en {status} !',
    addedToStatusPlural: '{count} puzzles ajoutés en {status} !',
    alreadyInCollection: 'Ces puzzles sont déjà dans votre collection',
    addError: "Erreur lors de l'ajout",
    minimum: 'Minimum',
    maximum: 'Maximum',

    // EventModal
    loginToRegister: 'Connectez-vous pour vous inscrire',
    alreadyRegistered: 'Vous êtes déjà inscrit à cet événement',
    eventFull: 'Cet événement est complet',
    registrationConfirmed: 'Inscription confirmée ! 🎉',
    registrationError: 'Erreur lors de l\'inscription',
    registering: 'Inscription...',
    alreadyRegisteredBtn: 'Déjà inscrit',
    eventFullBtn: 'Événement complet',
    loginToRegisterBtn: 'Connectez-vous pour vous inscrire',
    registerBtn: 'S\'inscrire',
    aboutEvent: 'À propos de l\'événement',
    moreInfoEvents: 'Plus d\'infos sur tous les événements',
    participants: 'participants',

    // EventCard
    full: 'Complet',

    // PostCard
    trending: 'Tendance',
    puzzleCompleted: 'Puzzle complété',
    viewDetails: '→ Voir détails',
    puzzleBrandLabel: 'Marque: ',
    puzzlePiecesLabel: 'Pièces: ',
    puzzleCategoryLabel: 'Catégorie: ',
    puzzleRefLabel: 'Réf: ',
    iLike: 'J\'aime',
    notLiked: 'Pas aimé',
    following2: 'Suivi',
    follow2: 'Suivre',
    loginToLike: 'Connectez-vous pour aimer les posts',
    loginToWishlist: 'Connectez-vous pour ajouter à la wishlist',
    loginToFollow: 'Connectez-vous pour suivre des utilisateurs',
    loginToLikePuzzle: 'Connectez-vous pour liker des puzzles',
    loginToDislikePuzzle: 'Connectez-vous pour disliker des puzzles',
    removedFromWishlist: 'Retiré de votre wishlist',
    addedToWishlist: 'Ajouté à votre wishlist!',
    wishlistUpdateFailed: 'Échec de la mise à jour de la wishlist',
    unfollowed: 'Suivi retiré',
    followedUser: 'Vous suivez cet utilisateur',
    followUpdateFailed: 'Échec de la mise à jour du suivi',
    dislikeRemoved: 'Dislike retiré',
    puzzleDisliked: 'Puzzle disliké',
    puzzleAddedToWishlist: '✨ Puzzle ajouté à votre wishlist !',
    puzzleRemovedFromWishlist: 'Puzzle retiré de votre wishlist',
    updateFailed: 'Échec de la mise à jour',
    likeUpdateFailed: 'Échec de la mise à jour du like',

    // CreatePostForm
    sharePuzzlePassion: 'Partagez votre passion pour les puzzles...',
    scanPuzzleBtn: 'Scanner Puzzle',
    scannedPuzzle: 'Puzzle scanné',
    puzzleBrandField: 'Marque: ',
    puzzlePiecesField: 'Pièces: ',
    puzzleRefField: 'Réf: ',
    addPersonalPhoto: 'Ajoutez votre photo personnelle du puzzle terminé',
    addMyPhoto: 'Ajouter ma photo',
    publishingBtn: 'Publication...',
    publishBtn: 'Publier',
    puzzleScanned: 'Puzzle scanné ! Ajoutez maintenant votre photo personnelle 📸',
    noContent: 'Veuillez ajouter du contenu',
    noPhoto: 'Veuillez ajouter une photo',
    missingFields: 'Champs manquants: ',
    postCreated: 'Post créé avec succès!',
    postFailed: 'Échec de la création du post. Veuillez réessayer.',

    // CollectionSection
    inBox2: 'Boîte',
    completedTab: 'Terminés',
    sortByBtn: 'Trier par',
    dateNewest: 'Date (Plus récent)',
    dateOldest: 'Date (Plus ancien)',
    piecesAscSort: 'Pièces (Croissant)',
    piecesDescSort: 'Pièces (Décroissant)',
    noInboxPuzzle: 'Aucun puzzle dans sa boîte',
    scanToAdd: 'Scannez vos puzzles pour les ajouter ici',
    noCompletedPuzzle: 'Aucun puzzle terminé',
    completeFirstPuzzle: 'Complétez vos premiers puzzles pour les voir ici',
    changeMyPhoto: 'Changer ma photo',
    addMyPhotoBtn: 'Ajouter ma photo',
    photoAdded: '📸 Photo ajoutée !',
    uploadError: 'Erreur lors de l\'upload',
    xpGained: '🎉 +100 XP ! Puzzle terminé !',
    puzzleBoxed: 'Puzzle mis dans sa boîte !',
    puzzleWishlisted: 'Puzzle mis en wishlist !',
    updateError: 'Erreur lors de la mise à jour',
    removeConfirm: 'Êtes-vous sûr de vouloir retirer ce puzzle de votre collection ?',
    removeSuccess: 'Puzzle retiré de votre collection',
    removeError: 'Erreur lors de la suppression',
    removeFromCollection: 'Retirer de ma collection',
    puzzlePiecesCount: 'pièces',
    puzzleRef: 'Réf: ',
    byBrand: 'par ',
    startedOn: 'Commencé le : ',
    completedOn: 'Terminé le : ',
    inTheBox: '📦 Dans la boîte',
    completedStatus: '✅ Terminé',

    // Common
    loading: 'Chargement...',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    share: 'Partager',
    like: 'J\'aime',
    comment: 'Commenter',
    comments: 'Commentaires',
    addComment: 'Ajouter un commentaire...',
    noComments: 'Aucun commentaire pour le moment',
    search: 'Rechercher',
    close: 'Fermer',
    more: 'Plus...',
    move: 'Déplacer',
    movedTo: 'Déplacé vers',
    moveError: 'Erreur lors du déplacement',
    removedFromWishlist: 'Retiré de la wishlist',
    features: 'Caractéristiques :',
    viewOnAmazon: 'Voir le produit sur Amazon',
    amazonDisclaimer: 'En tant que Partenaire Amazon, nous réalisons un bénéfice sur les achats qualifiés',
    loadError: 'Impossible de charger les détails',
    // EditProfileDialog
    editProfile: 'Modifier le profil',
    profilePhoto: 'Photo de profil',
    coverPhoto: 'Photo de couverture',
    uploading: 'Upload en cours...',
    chooseImage: 'Choisir une image',
    chooseBanner: 'Choisir une bannière',
    recommended: 'Recommandé',
    profileUpdated: 'Profil mis à jour',
    imageUploaded: 'Image uploadée !',
    selectImageError: 'Veuillez sélectionner une image',
    imageTooLarge: 'Image trop grande (max 5MB)',
    // StatsModal
    unlocked: 'Débloqué',
    locked: 'Non débloqué',
    emptyWishlist: 'Aucun puzzle en wishlist',
    // Layout
    reportIssue: 'Signaler un problème',
    report: 'Signaler',
    footerTagline: 'Votre communauté puzzle ultime',
    footerCopyright: '© 2026 PuzzleWorld. Tous droits réservés.',
    privacyPolicyLabel: 'Politique de confidentialité',
    termsLabel: 'CGU',
    // DeleteAccount
    dangerZone: 'Zone Danger',
    deleteAccountDesc: 'La suppression de votre compte est irréversible. Toutes vos données (collection, posts, statistiques) seront définitivement effacées.',
    deleteAccount: 'Supprimer mon compte',
    confirmDeletion: 'Confirmer la suppression',
    irreversibleAction: 'Cette action est',
    irreversibleWord: 'irréversible',
    dataToBeDeleted: 'Les données suivantes seront supprimées:',
    profileData: 'Votre profil et informations personnelles',
    puzzleCollectionData: 'Votre collection de puzzles',
    postsCommentsData: 'Vos posts et commentaires (anonymisés)',
    likesData: 'Vos likes et favoris',
    statsData: 'Vos statistiques et badges',
    subscriptionsData: 'Vos abonnements',
    deleting: 'Suppression...',
    confirmDelete: 'Confirmer la suppression',
    deletionInProgress: 'Suppression en cours...',
    accountDeleted: 'Compte supprimé avec succès',
    deletionError: 'Erreur lors de la suppression',
    // Profile bug report section
    reportIssueSubtitle: 'Un bug, une suggestion ou un contenu incorrect ? Faites-le nous savoir.',
    deletedUser: 'Utilisateur supprimé',
    deletedContent: '[Contenu supprimé par l\'utilisateur]',
  },
  en: {
    // Navigation
    home: 'Home',
    discover: 'Discover',
    social: 'Social',
    collection: 'Collection',
    online: 'Online',
    profile: 'Profile',
    logOut: 'Log Out',
    logIn: 'Log In',
    
    // Home Page
    heroTitle: 'Your Ultimate Puzzle Community',
    heroSubtitle: 'Connect with thousands of puzzle enthusiasts, share your creations, and discover exciting new challenges',
    startCollection: 'Start Your Collection',
    exploreCollection: 'Explore Collection',
    featuredPuzzles: 'Featured Puzzles',
    mostPlayed: 'Most Played',
    monthlyEvents: 'Monthly Events',
    communityFeed: 'Community Feed',
    viewAll: 'View All',
    
    // Collection Page
    puzzleCollection: 'Puzzle Collection',
    explorePuzzles: 'Explore {count} puzzles',
    searchPuzzles: 'Search puzzles...',
    filters: 'Filters',
    all: 'All',
    nature: 'Nature',
    abstract: 'Abstract',
    urban: 'Urban',
    space: 'Space',
    architecture: 'Architecture',
    vintage: 'Vintage',
    animals: 'Animals',
    art: 'Art',
    pieceCount: 'Piece Count',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    clearAllFilters: 'Clear All Filters',
    mostPopular: 'Most Popular',
    newest: 'Newest',
    highestRated: 'Highest Rated',
    piecesLowToHigh: 'Pieces: Low to High',
    piecesHighToLow: 'Pieces: High to Low',
    backToTop: 'Back to Top',
    sortBy: 'Sort by',
    
    // Social Page
    community: 'Community',
    trending: 'Trending',
    latest: 'Latest',
    following: 'Following',
    createPost: 'Create Post',
    whatsOnYourMind: 'What\'s on your mind?',
    shareYourThoughts: 'Share your thoughts...',
    uploadImage: 'Upload Image',
    completedPuzzle: 'Completed Puzzle?',
    puzzleName: 'Puzzle Name',
    brand: 'Brand',
    pieces: 'Pieces',
    post: 'Post',
    posting: 'Posting...',
    logInToPost: 'Please log in to create posts and interact with the community',
    noPosts: 'No posts yet. Be the first to share!',
    youveReachedEnd: 'You\'ve reached the end!',
    communityGuidelines: 'Community Guidelines',
    guidelinesText: 'Be respectful, share your passion, and help fellow puzzlers. Let\'s keep this community awesome! 🧩',
    communityStats: 'Community Stats',
    totalPosts: 'Total Posts',
    activeToday: 'Active Today',
    live: 'Live',
    
    // Profile Page
    welcomeProfile: 'Welcome to PuzzleWorld',
    logInToViewProfile: 'Log in to view your profile, track completed puzzles, and manage your wishlist',
    joined: 'Joined',
    completed: 'Completed',
    hours: 'Hours',
    achievements: 'Achievements',
    wishlist: 'Wishlist',
    level: 'Level',
    puzzleEnthusiast: 'Puzzle Enthusiast',
    puzzleExpert: 'Puzzle Expert',
    puzzleMaster: 'Puzzle Master',
    noAchievements: 'No achievements yet',
    completeToUnlock: 'Complete puzzles to unlock badges!',
    welcomeToDashboard: 'Welcome to your puzzle journey dashboard! Track your completed puzzles and build your wishlist.',
    myEvents: 'My Events',
    upcomingEvents: 'Upcoming Events',
    noEvents: 'No events registered',
    
    // Online Puzzles Page
    onlinePuzzles: 'Online Puzzles',
    playInBrowser: 'Play puzzles directly in your browser',
    searchGames: 'Search games...',
    web: 'Web',
    mobile: 'Mobile',
    crossPlatform: 'Cross-Platform',
    featured: 'Featured',
    playNow: 'Play Now',
    players: 'players',
    trendingNow: 'Trending Now',
    popularThisWeek: 'Most popular puzzle games this week',
    allOnlineGames: 'All Online Games',
    browseCollection: 'Browse our complete collection',
    wantToAddGame: 'Want to add a game?',
    addGameText: 'Know of an amazing online puzzle game that should be featured here? Let us know and we\'ll review it for inclusion!',
    suggestGame: 'Suggest a Game',
    
    // Puzzle Detail Page
    backToCollection: 'Back to Collection',
    playOnline: 'Play Online',
    download: 'Download',
    overview: 'Overview',
    leaderboard: 'Leaderboard',
    reviews: 'Reviews',
    aboutPuzzle: 'About this Puzzle',
    avgTime: 'Average Time',
    bestTime: 'Best Time',
    createdBy: 'Created by',
    followers: 'followers',
    follow: 'Follow',
    viewProfile: 'View Profile',
    reportPuzzle: 'Report this puzzle',
    youMightLike: 'You Might Also Like',
    viewMore: 'View More',
    foundHelpful: 'found helpful',
    
    // Friends & Messages
    friendsAndMessages: 'Friends & Messages',
    manageFriendsConversations: 'Manage your friends and conversations',
    friends: 'Friends',
    messages: 'Messages',
    received: 'Received',
    sent: 'Sent',
    findFriends: 'Find',
    noFriendsYet: 'You have no friends yet',
    addFriendsToChatPrompt: 'Add friends to start chatting',
    conversations: 'Conversations',
    startConversation: 'Start the conversation!',
    selectFriendToChat: 'Select a friend to chat',
    writeMessage: 'Write a message...',
    noPendingRequests: 'No pending received requests',
    noSentRequests: 'No pending sent requests',
    pendingResponse: 'Awaiting response',
    searchByNameOrCode: 'Search by name or friend code...',
    typeAtLeast2Chars: 'Type at least 2 characters to search',
    requestSent: 'Request sent',
    requestAccepted: 'Request accepted',
    requestDeleted: 'Request removed',
    friendRemoved: 'Friend removed',
    addFriend: 'Add',
    friend: 'Friend',
    pending: 'Pending',
    cancel: 'Cancel',
    unregisterFromEvent: 'Unregister',
    unregistering: 'Unregistering...',
    eventEnded: 'Ended',
    pastEvents: 'Past events',
    registerForEventsPrompt: 'Register for events to see them here',
    accountSettings: 'Account settings',
    totalPiecesAssembled: 'pieces assembled in total',
    puzzlesCompleted: 'completed',
    followings: 'Following',
    myCollection: 'My Collection',
    followers: 'Followers',
    followings: 'Following',
    // Events Page
    eventsTitle: 'Events',
    eventsSubtitle: 'Join our community at exclusive events',
    sortEarliest: '📅 Earliest first',
    sortLatest: '📅 Latest first',
    noEventsAvailable: 'No events available at the moment',
    noEventsComingSoon: 'Check back soon to discover our upcoming events!',
    // Profile hardcoded strings
    piecesAssembled: 'pieces assembled in total',
    puzzlesCompletedLabel: 'completed',
    myCollectionTab: 'My Collection',
    personalTab: 'Personal',
    pastEventsLabel: 'Past events',
    registerForEventsHint: 'Register for events to see them here',
    eventEnded: 'Ended',
    unregisterConfirm: 'Are you sure you want to unregister from this event?',
    unregisterError: 'Error during unregistration',

    // Home Page hardcoded
    newPuzzlesDaily: 'New puzzles every day',
    newPuzzlesDailyLong: 'New puzzles added every day',
    scanPuzzle: 'Scan',
    addPuzzle: 'Add a puzzle',
    explore: 'Explore',
    topPuzzles: 'Top 10 Puzzles',
    mostLiked: 'Most liked',
    mostLikedCommunity: 'Most liked by the community',
    latestArticles: 'Latest Articles',
    mustRead: 'Must read',
    upcomingEvents: 'Upcoming Events',
    dontMissAnything: 'Don\'t miss anything from the community',
    addYourPuzzle: 'Add your puzzle',
    scanOrAddManually: 'Scan the barcode or add manually',
    exploreCollection: 'Explore the collection',
    discoverThousands: 'Discover thousands of puzzles',
    noPuzzleAvailable: 'No puzzles available',
    noArticleYet: 'No articles yet',
    noEventAvailable: 'No events available',
    eventsInMaintenance: 'Events under maintenance',
    eventsMaintenanceLong: 'Events are temporarily under maintenance.',
    comingSoon: 'Check back soon!',
    comingSoonLong: 'Check back soon to discover our upcoming events!',
    seeAll: 'See all',
    upcoming: 'Upcoming',

    // Collection Page hardcoded
    communityCollection: 'Community Collection',
    communityPuzzlesCount: '{count} puzzles shared by the community',
    discoverMode: 'Discovery Mode',
    globalCollection: 'Global collection',
    sortNewest: 'Newest',
    sortPopular: 'Popular',
    piecesAsc: 'Pieces ↑',
    piecesDesc: 'Pieces ↓',
    piecesAscFull: 'Pieces (ascending)',
    piecesDescFull: 'Pieces (descending)',
    sortBy2: 'Sort by:',
    brandFilter: 'Brand',
    allBrands: 'All',
    unknownBrand: '❓ Unknown brand',
    multipleSelect: 'Multi-select',
    addToCollection: 'Add',
    inBox: 'In the box',
    completed2: 'Completed',
    myBox: 'My box',
    noPuzzleFound: 'No puzzles found',
    beFirstToAdd: 'Be the first to add a puzzle to the community!',
    selected: 'selected',
    selectedPlural: 'selected',
    deselectAll: 'Deselect',
    selectAll: 'All',
    loginToAdd: 'Log in to add to your collection',
    addedToStatus: '{count} puzzle added to {status}!',
    addedToStatusPlural: '{count} puzzles added to {status}!',
    alreadyInCollection: 'These puzzles are already in your collection',
    addError: 'Error while adding',
    minimum: 'Minimum',
    maximum: 'Maximum',

    // EventModal
    loginToRegister: 'Log in to register',
    alreadyRegistered: 'You are already registered for this event',
    eventFull: 'This event is full',
    registrationConfirmed: 'Registration confirmed! 🎉',
    registrationError: 'Error during registration',
    registering: 'Registering...',
    alreadyRegisteredBtn: 'Already registered',
    eventFullBtn: 'Event full',
    loginToRegisterBtn: 'Log in to register',
    registerBtn: 'Register',
    aboutEvent: 'About this event',
    moreInfoEvents: 'More info on all events',
    participants: 'participants',

    // EventCard
    full: 'Full',

    // PostCard
    trending: 'Trending',
    puzzleCompleted: 'Puzzle completed',
    viewDetails: '→ View details',
    puzzleBrandLabel: 'Brand: ',
    puzzlePiecesLabel: 'Pieces: ',
    puzzleCategoryLabel: 'Category: ',
    puzzleRefLabel: 'Ref: ',
    iLike: 'Like',
    notLiked: 'Not liked',
    following2: 'Following',
    follow2: 'Follow',
    loginToLike: 'Log in to like posts',
    loginToWishlist: 'Log in to add to wishlist',
    loginToFollow: 'Log in to follow users',
    loginToLikePuzzle: 'Log in to like puzzles',
    loginToDislikePuzzle: 'Log in to dislike puzzles',
    removedFromWishlist: 'Removed from your wishlist',
    addedToWishlist: 'Added to your wishlist!',
    wishlistUpdateFailed: 'Failed to update wishlist',
    unfollowed: 'Unfollowed',
    followedUser: 'You are now following this user',
    followUpdateFailed: 'Failed to update follow',
    dislikeRemoved: 'Dislike removed',
    puzzleDisliked: 'Puzzle disliked',
    puzzleAddedToWishlist: '✨ Puzzle added to your wishlist!',
    puzzleRemovedFromWishlist: 'Puzzle removed from your wishlist',
    updateFailed: 'Failed to update',
    likeUpdateFailed: 'Failed to update like',

    // CreatePostForm
    sharePuzzlePassion: 'Share your passion for puzzles...',
    scanPuzzleBtn: 'Scan Puzzle',
    scannedPuzzle: 'Scanned puzzle',
    puzzleBrandField: 'Brand: ',
    puzzlePiecesField: 'Pieces: ',
    puzzleRefField: 'Ref: ',
    addPersonalPhoto: 'Add your personal photo of the finished puzzle',
    addMyPhoto: 'Add my photo',
    publishingBtn: 'Publishing...',
    publishBtn: 'Publish',
    puzzleScanned: 'Puzzle scanned! Now add your personal photo 📸',
    noContent: 'Please add some content',
    noPhoto: 'Please add a photo',
    missingFields: 'Missing fields: ',
    postCreated: 'Post created successfully!',
    postFailed: 'Failed to create post. Please try again.',

    // CollectionSection
    inBox2: 'Box',
    completedTab: 'Completed',
    sortByBtn: 'Sort by',
    dateNewest: 'Date (Newest)',
    dateOldest: 'Date (Oldest)',
    piecesAscSort: 'Pieces (Ascending)',
    piecesDescSort: 'Pieces (Descending)',
    noInboxPuzzle: 'No puzzles in the box',
    scanToAdd: 'Scan your puzzles to add them here',
    noCompletedPuzzle: 'No completed puzzles',
    completeFirstPuzzle: 'Complete your first puzzles to see them here',
    changeMyPhoto: 'Change my photo',
    addMyPhotoBtn: 'Add my photo',
    photoAdded: '📸 Photo added!',
    uploadError: 'Upload error',
    xpGained: '🎉 +100 XP! Puzzle completed!',
    puzzleBoxed: 'Puzzle moved to box!',
    puzzleWishlisted: 'Puzzle added to wishlist!',
    updateError: 'Error updating',
    removeConfirm: 'Are you sure you want to remove this puzzle from your collection?',
    removeSuccess: 'Puzzle removed from your collection',
    removeError: 'Error removing puzzle',
    removeFromCollection: 'Remove from collection',
    puzzlePiecesCount: 'pieces',
    puzzleRef: 'Ref: ',
    byBrand: 'by ',
    startedOn: 'Started on: ',
    completedOn: 'Completed on: ',
    inTheBox: '📦 In the box',
    completedStatus: '✅ Completed',

    // Common
    loading: 'Loading...',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    share: 'Share',
    like: 'Like',
    comment: 'Comment',
    comments: 'Comments',
    addComment: 'Add a comment...',
    noComments: 'No comments yet',
    search: 'Search',
    close: 'Close',
    more: 'More...',
    move: 'Move',
    movedTo: 'Moved to',
    moveError: 'Error while moving',
    removedFromWishlist: 'Removed from wishlist',
    features: 'Features:',
    viewOnAmazon: 'View product on Amazon',
    amazonDisclaimer: 'As an Amazon Associate, we earn from qualifying purchases',
    loadError: 'Unable to load details',
    // EditProfileDialog
    editProfile: 'Edit profile',
    profilePhoto: 'Profile photo',
    coverPhoto: 'Cover photo',
    uploading: 'Uploading...',
    chooseImage: 'Choose an image',
    chooseBanner: 'Choose a banner',
    recommended: 'Recommended',
    profileUpdated: 'Profile updated',
    imageUploaded: 'Image uploaded!',
    selectImageError: 'Please select an image',
    imageTooLarge: 'Image too large (max 5MB)',
    // StatsModal
    unlocked: 'Unlocked',
    locked: 'Locked',
    emptyWishlist: 'No puzzles in wishlist',
    // Layout
    reportIssue: 'Report an issue',
    report: 'Report',
    footerTagline: 'Your ultimate puzzle community',
    footerCopyright: '© 2026 PuzzleWorld. All rights reserved.',
    privacyPolicyLabel: 'Privacy Policy',
    termsLabel: 'Terms',
    // DeleteAccount
    dangerZone: 'Danger Zone',
    deleteAccountDesc: 'Deleting your account is irreversible. All your data (collection, posts, statistics) will be permanently deleted.',
    deleteAccount: 'Delete my account',
    confirmDeletion: 'Confirm deletion',
    irreversibleAction: 'This action is',
    irreversibleWord: 'irreversible',
    dataToBeDeleted: 'The following data will be deleted:',
    profileData: 'Your profile and personal information',
    puzzleCollectionData: 'Your puzzle collection',
    postsCommentsData: 'Your posts and comments (anonymized)',
    likesData: 'Your likes and bookmarks',
    statsData: 'Your statistics and badges',
    subscriptionsData: 'Your subscriptions',
    deleting: 'Deleting...',
    confirmDelete: 'Confirm deletion',
    deletionInProgress: 'Deletion in progress...',
    accountDeleted: 'Account successfully deleted',
    deletionError: 'Error during deletion',
    // Profile bug report section
    reportIssueSubtitle: 'A bug, a suggestion or incorrect content? Let us know.',
    deletedUser: 'Deleted user',
    deletedContent: '[Content deleted by user]',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    // Trigger a custom event when language changes
    window.dispatchEvent(new CustomEvent('languageChange', { detail: language }));
  }, [language]);

  const t = (key, params = {}) => {
    let text = translations[language][key] || key;
    // Replace {param} placeholders
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}